export const THESES = [
  "Andare a letto alle 20:00 è meglio che alle 24:00.",
  "La pizza con l'ananas è una delizia culinaria.",
  "I gatti sono migliori dei cani come animali domestici.",
  "I videogiochi dovrebbero essere una materia scolastica.",
  "L'inverno è la stagione migliore dell'anno.",
  "I social media hanno migliorato le relazioni umane.",
  "Viaggiare nel tempo sarebbe un disastro.",
  "I supereroi farebbero più danni che benefici nella realtà.",
  "Il libro è sempre meglio del film.",
  "La tecnologia ci sta rendendo meno intelligenti.",
  "Sarebbe meglio vivere senza soldi in un'economia del baratto.",
  "Gli alieni esistono e ci stanno osservando.",
  "La colazione non è il pasto più importante della giornata.",
  "Essere famosi è una maledizione.",
  "L'intelligenza artificiale conquisterà il mondo.",
  "I fantasmi esistono.",
  "È meglio sapere la verità che essere felici.",
  "La scuola dovrebbe insegnare come pagare le tasse invece di algebra.",
  "I vestiti di marca sono uno spreco di soldi.",
  "Dovremmo colonizzare Marte il prima possibile.",
  "Cucinare a casa è meglio che mangiare fuori.",
  "Il lavoro ideale non dovrebbe esistere.",
  "Le vacanze brevi sono migliori di quelle lunghe.",
  "Il silenzio è sottovalutato.",
  "Vivere in città è più stressante che vivere in campagna.",
  "Le serie TV sono diventate troppo lunghe.",
  "Il contante dovrebbe sparire.",
  "Il talento conta meno della costanza.",
  "La nostalgia rovina il presente.",
  "Fare sport dovrebbe essere obbligatorio a scuola.",
  "L’arte dovrebbe essere gratuita per tutti.",
  "Le riunioni sono quasi sempre inutili.",
  "Il sonno è più importante della produttività.",
  "Le app di dating rendono le relazioni più superficiali.",
  "La semplicità è la vera forma di lusso.",
  "I bambini dovrebbero usare meno tecnologia.",
  "La libertà totale non esiste.",
  "Il successo non porta automaticamente felicità.",
  "Le regole esistono per essere infrante.",
  "Il futuro farà paura quanto il passato.",
];
